services:
  app:
    container_name: listings-api
    build: .
    # enable this for development
    # command: ["fastapi", "dev", "src/app/main.py"]
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@postgres:5432/listings
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - postgres
      - migration

  migration :
    container_name: listings-migration
    build: .
    command: ["alembic", "upgrade", "head"]
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@postgres:5432/listings
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: listings
    ports:
      - "5432:5432"
