"""Create Models

Revision ID: b1ff07458555
Revises: 
Create Date: 2025-01-18 21:52:47.893604

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1ff07458555'
down_revision: str| None = None
branch_labels: str| Sequence[str] |None = None
depends_on: str| Sequence[str] |None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_dataset_entities',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_listings',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dataset_entity_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('image_hashes', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('test_properties',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('test_property_values_bool',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['test_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['test_properties.property_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'property_id')
    )
    op.create_table('test_property_values_str',
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['test_listings.listing_id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['test_properties.property_id'], ),
    sa.PrimaryKeyConstraint('listing_id', 'property_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_property_values_str')
    op.drop_table('test_property_values_bool')
    op.drop_table('test_properties')
    op.drop_table('test_listings')
    op.drop_table('test_dataset_entities')
    # ### end Alembic commands ###
